import { poppins } from "./ui/fonts";
import "./globals.css";
import Footer from "./ui/Footer";
import Header from "./ui/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
      <Header></Header>
        {children}
      <Footer></Footer>
      </body>
    </html>
  );
}
